/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// Details about why a request failed, such as missing or invalid parameters
type ApiError struct {

	// A \"slug\" that serves as the error code (eg. \"bad_parameter\")
	Error_ string `json:"error,omitempty"`

	ErrorDetail []ErrorDetail `json:"error_detail,omitempty"`

	// A user-friendly description of the error (appropriate to show to an end-user)
	ErrorDescription string `json:"error_description,omitempty"`
}
