/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type CancellationCostError struct {

	// Total price of the ride
	Amount int32 `json:"amount,omitempty"`

	// The ISO 4217 currency code for the amount (e.g. USD)
	Currency string `json:"currency,omitempty"`

	// The description for the cost
	Description string `json:"description,omitempty"`

	// Token used to confirm the fee when cancelling a request
	Token string `json:"token,omitempty"`

	// How long, in seconds, before the token expires
	TokenDuration int32 `json:"token_duration,omitempty"`

	// A \"slug\" that serves as the error code (eg. \"bad_parameter\")
	Error_ string `json:"error,omitempty"`

	ErrorDetail []ErrorDetail `json:"error_detail,omitempty"`

	// A user-friendly description of the error (appropriate to show to an end-user)
	ErrorDescription string `json:"error_description,omitempty"`
}
