/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type Charge struct {

	// The line item amount
	Amount int32 `json:"amount,omitempty"`

	// The currency for the amount
	Currency string `json:"currency,omitempty"`

	// The payment method display name.
	PaymentMethod string `json:"payment_method,omitempty"`
}
