/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// A non-guaranteed estimate of price
type CostEstimate struct {

	RideType RideTypeEnum `json:"ride_type,omitempty"`

	// A human readable description of the ride type
	DisplayName string `json:"display_name,omitempty"`

	// The ISO 4217 currency code for the amount (e.g. 'USD')
	Currency string `json:"currency,omitempty"`

	// Estimated lower bound for trip cost, in minor units (cents). Estimates are not guaranteed, and only provide a reasonable range based on current conditions. 
	EstimatedCostCentsMin int32 `json:"estimated_cost_cents_min,omitempty"`

	// Estimated upper bound for trip cost, in minor units (cents). Estimates are not guaranteed, and only provide a reasonable range based on current conditions. 
	EstimatedCostCentsMax int32 `json:"estimated_cost_cents_max,omitempty"`

	// Estimated distance for this trip 
	EstimatedDistanceMiles float64 `json:"estimated_distance_miles,omitempty"`

	// Estimated time to get from the start location to the end. 
	EstimatedDurationSeconds int32 `json:"estimated_duration_seconds,omitempty"`

	// The validity of the cost estimate returned
	IsValidEstimate bool `json:"is_valid_estimate"`

	// Current Prime Time Percentage. Prime Time adds a percentage to ride costs, prior to other applicable fees. When ride requests greatly outnumber available drivers, our system will automatically turn on Prime Time. If Prime Time is inactive, the value returned will be '0%'. Note: The returned estimate already has Prime Time factored in. The value is returned here for reference and to allow users to confirm/accept Prime Time prior to initiating a ride. 
	PrimetimePercentage string `json:"primetime_percentage,omitempty"`

	// This token is needed when requesting rides. See 'Request a Lyft' for more details
	PrimetimeConfirmationToken string `json:"primetime_confirmation_token,omitempty"`
}
