/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type Cost struct {

	// Total price of the ride
	Amount int32 `json:"amount,omitempty"`

	// The ISO 4217 currency code for the amount (e.g. USD)
	Currency string `json:"currency,omitempty"`

	// The description for the cost
	Description string `json:"description,omitempty"`
}
