/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type DriverDetail struct {

	// The driver's first name
	FirstName string `json:"first_name,omitempty"`

	// The driver's contact phone number. Must be E.164 formatted. 
	PhoneNumber string `json:"phone_number,omitempty"`

	// The driver's rating based in 0-5 scale
	Rating string `json:"rating,omitempty"`

	// The driver's image url
	ImageUrl string `json:"image_url,omitempty"`
}
