/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// An object with a single key-value pair, where the key is the name of the invalid parameter, and the value is a description of the error. 
type ErrorDetail struct {

	// description of the error
	FieldName string `json:"field_name,omitempty"`
}
