/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type LineItem struct {

	// The line item display name for a charge item
	Type_ string `json:"type,omitempty"`

	// The line item amount
	Amount int32 `json:"amount,omitempty"`

	// The currency for the amount
	Currency string `json:"currency,omitempty"`
}
