/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type NearbyDriver struct {

	// the lastest recorded driver locations up to 5 sorted in chronological order.
	Locations []LatLng `json:"locations,omitempty"`
}
