/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

import (
	"time"
)

type PickupDropoffLocation struct {

	// The latitude component of a location
	Lat float64 `json:"lat,omitempty"`

	// The longitude component of a location
	Lng float64 `json:"lng,omitempty"`

	// A human readable address at/near the given location
	Address string `json:"address,omitempty"`

	// Server time when the location object is created
	Time time.Time `json:"time,omitempty"`
}
