/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type PricingDetails struct {

	// The base charge of the trip
	BaseCharge int32 `json:"base_charge,omitempty"`

	// The charge amount if cancel penalty is involved
	CancelPenaltyAmount int32 `json:"cancel_penalty_amount,omitempty"`

	// The minimum charge for the trip
	CostMinimum int32 `json:"cost_minimum,omitempty"`

	// The cost per mile
	CostPerMile int32 `json:"cost_per_mile,omitempty"`

	// The cost per minute
	CostPerMinute int32 `json:"cost_per_minute,omitempty"`

	// The ISO 4217 currency code for the amount (e.g. USD)
	Currency string `json:"currency,omitempty"`

	// Service fee
	TrustAndService int32 `json:"trust_and_service,omitempty"`
}
