/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// Represents the general information about a user.
type Profile struct {

	// The unique ID of this user
	Id string `json:"id,omitempty"`

	// The first name of this user
	FirstName string `json:"first_name,omitempty"`

	// The last name of this user
	LastName string `json:"last_name,omitempty"`

	// Indicates whether this user has taken at least one Lyft ride
	HasTakenARide bool `json:"has_taken_a_ride"`
}
