/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// Rating and optional feedback and tip
type RatingRequest struct {

	// The passenger's rating of this ride from 1 to 5
	Rating int32 `json:"rating,omitempty"`

	// The passenger's written feedback about this ride
	Feedback string `json:"feedback,omitempty"`

	// Tip amount in minor units and tip currency
	Tip interface{} `json:"tip,omitempty"`
}
