/*
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// Types of rides offered via Lyft
type RideTypeEnumWithOther string

const (
	RideTypeWithOtherLyft        RideTypeEnumWithOther = "lyft"
	RideTypeWithOtherLyftLine    RideTypeEnumWithOther = "lyft_line"
	RideTypeWithOtherLyftPlus    RideTypeEnumWithOther = "lyft_plus"
	RideTypeWithOtherLyftSUV     RideTypeEnumWithOther = "lyft_suv"
	RideTypeWithOtherLyftPremier RideTypeEnumWithOther = "lyft_premier"
	RideTypeWithOtherLyftLux     RideTypeEnumWithOther = "lyft_lux"
	RideTypeWithOtherLyftLuxSUV  RideTypeEnumWithOther = "lyft_luxsuv"
	RideTypeWithOther            RideTypeEnumWithOther = "other"
)
