/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// Minimal set of ride details
type RideRequest struct {

	// The ID of the requested ride
	RideId string `json:"ride_id,omitempty"`

	Status RideStatusEnum `json:"status,omitempty"`

	// The *requested* location for passenger pickup
	Origin interface{} `json:"origin,omitempty"`

	// The *requested* location for passenger drop off
	Destination interface{} `json:"destination,omitempty"`

	Passenger PassengerDetail `json:"passenger,omitempty"`
}
