/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

import (
	"time"
)

// Detail information about a ride
type RideDetail struct {

	// The unique ID of this ride
	RideId string `json:"ride_id,omitempty"`

	Status RideStatusEnum `json:"status,omitempty"`

	RideType RideTypeEnumWithOther `json:"ride_type,omitempty"`

	Passenger PassengerDetail `json:"passenger,omitempty"`

	Driver DriverDetail `json:"driver,omitempty"`

	Vehicle VehicleDetail `json:"vehicle,omitempty"`

	// The *requested* location for passenger pickup
	Origin interface{} `json:"origin,omitempty"`

	// The *requested* location for passenger drop off
	Destination interface{} `json:"destination,omitempty"`

	// The *actual* location of passenger pickup
	Pickup interface{} `json:"pickup,omitempty"`

	// The *actual* location of passenger drop off
	Dropoff interface{} `json:"dropoff,omitempty"`

	// The *current* location info of the ride
	Location interface{} `json:"location,omitempty"`

	// The Prime Time percentage applied to the base price
	PrimetimePercentage string `json:"primetime_percentage,omitempty"`

	// The distance, in miles, that this ride traveled. This field is only present after drop-off
	DistanceMiles float32 `json:"distance_miles,omitempty"`

	// Duration of the ride in seconds from pickup to drop-off. This field is only present after drop-off.
	DurationSeconds int32 `json:"duration_seconds,omitempty"`

	// The total price for the current ride
	Price interface{} `json:"price,omitempty"`

	// The break down of cost
	LineItems []LineItem `json:"line_items,omitempty"`

	CanCancel []string `json:"can_cancel,omitempty"`

	// The role of user who canceled the ride (if applicable)
	CanceledBy string `json:"canceled_by,omitempty"`

	// The cost of cancellation if there would be a penalty
	CancellationPrice interface{} `json:"cancellation_price,omitempty"`

	// The rating the user left for this ride, from 1 to 5
	Rating int32 `json:"rating,omitempty"`

	// The written feedback the user left for this ride
	Feedback string `json:"feedback,omitempty"`

	// The web view showing the pricing structure for the geographic area where the ride was taken          
	PricingDetailsUrl string `json:"pricing_details_url,omitempty"`

	// The web view showing the passenger, driver, and route for this ride. This field will only be present for rides created through this API, or that have been shared through the \"Share my Route\" feature 
	RouteUrl string `json:"route_url,omitempty"`

	// The ride requested timestamp in date and time
	RequestedAt time.Time `json:"requested_at,omitempty"`

	// The request timestamp in date and time
	GeneratedAt time.Time `json:"generated_at,omitempty"`

	// Indicates whether the ride was requested from the business profile or personal profile of the user. 
	RideProfile interface{} `json:"ride_profile,omitempty"`

	// Hex color code of the driver AMP device.
	BeaconColor string `json:"beacon_color,omitempty"`
}
