/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// Details about why a request failed, such as missing or invalid parameters
type RideRequestError struct {

	// A \"slug\" that serves as the error code (eg. \"bad_parameter\")
	Error_ string `json:"error,omitempty"`

	ErrorDetail []ErrorDetail `json:"error_detail,omitempty"`

	// A user-friendly description of the error (appropriate to show to an end-user)
	ErrorDescription string `json:"error_description,omitempty"`

	// Current Prime Time percentage
	PrimetimePercentage string `json:"primetime_percentage,omitempty"`

	// Current Prime Time multiplier (eg. if primetime_percentage is 100%, primetime_multiplier will be 2.0)
	PrimetimeMultiplier float32 `json:"primetime_multiplier,omitempty"`

	// A token that confirms the user has accepted current Prime Time charges
	PrimetimeConfirmationToken string `json:"primetime_confirmation_token,omitempty"`

	// Reserved for future use
	CostToken string `json:"cost_token,omitempty"`

	// Validity of the token in seconds
	TokenDuration string `json:"token_duration,omitempty"`
}
