/*
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// The current status of the ride
type RideStatusEnum string

const (
	RideStatusPending    RideStatusEnum = "pending"
	RideStatusAccepted   RideStatusEnum = "accepted"
	RideStatusArrived    RideStatusEnum = "arrived"
	RideStatusPickedUp   RideStatusEnum = "pickedUp"
	RideStatusDroppedOff RideStatusEnum = "droppedOff"
	RideStatusCanceled   RideStatusEnum = "canceled"
)
