/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

import (
	"time"
)

// Receipt information of a processed ride.
type RideReceipt struct {

	// The unique ID of this ride
	RideId string `json:"ride_id,omitempty"`

	// The total price for the current ride
	Price interface{} `json:"price,omitempty"`

	// The break down of line items
	LineItems []LineItem `json:"line_items,omitempty"`

	// The break down of charge method
	Charges []Charge `json:"charges,omitempty"`

	// The ride requested timestamp in date and time
	RequestedAt time.Time `json:"requested_at,omitempty"`

	// Indicates whether the ride was requested from the business profile or personal profile of the user. 
	RideProfile interface{} `json:"ride_profile,omitempty"`
}
