/*
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// The payment profile which the user has picked for the ride
type RideProfileEnum string

const (
	RideProfilePersonal RideProfileEnum = "personal"
	RideProfileBusiness RideProfileEnum = "business"
)
