/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type SandboxPrimetime struct {

	// The latitude component of a location
	Lat float64 `json:"lat,omitempty"`

	// The longitude component of a location
	Lng float64 `json:"lng,omitempty"`

	// The Prime Time to be applied as a string, e.g., '25%'
	PrimetimePercentage string `json:"primetime_percentage,omitempty"`
}
