/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

// Response when a sandbox ride is propagated through ride status
type SandboxRideUpdate struct {

	// The ID of the ride
	RideId string `json:"ride_id,omitempty"`

	Status RideStatusEnum `json:"status,omitempty"`
}
