/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type TipParams struct {

	// A tip for the driver in cents. To be charged to the user's default charge account.
	Amount int32 `json:"amount,omitempty"`

	// The currency in which you want to tip. e.g. USD
	Currency string `json:"currency,omitempty"`
}
