/* 
 * Lyft API
 *
 * Drive your app to success with Lyft's API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api-support@lyft.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package lyft

type VehicleDetail struct {

	// The vehicle's maker
	Make string `json:"make,omitempty"`

	// The vehicle's model
	Model string `json:"model,omitempty"`

	// The vehicle's model year
	Year int32 `json:"year,omitempty"`

	// The vehicle's license plate
	LicensePlate string `json:"license_plate,omitempty"`

	// The vehicle's license plate state
	LicensePlateState string `json:"license_plate_state,omitempty"`

	// The vehicle's color
	Color string `json:"color,omitempty"`

	// The vehicle's image url
	ImageUrl string `json:"image_url,omitempty"`
}
